### ISSUE TITLE
"Changes to" missing a lot of events, "On Event" is perfect.

### ISSUE THREAD

**Issue by ericvitale** [ady624/webCoRE#10]
When using "Changes to" as a trigger, it misses a lot of events. This has been verified by another forum member. However "On Event" works 100%. Seems to miss ~35% of events.

I created 3 pistons.

**Testing - Changes To** (import code: wdt3)
This piston increments a variable each time a virtual momentary button gets pressed. It detected it being pressed by using "Changes To".

![image](https://cloud.githubusercontent.com/assets/8474048/26562056/1c4a00bc-4491-11e7-839f-657419221e80.png)

**Testing - On Event** (import code: ciwc)
This piston increments a variable each time a virtual momentary button gets pressed. It detected it being pressed by using "On Event" then checks the variable "$currentEventValue" to see if it is "on".

![image](https://cloud.githubusercontent.com/assets/8474048/26562072/3cbb20f6-4491-11e7-806e-592882fce115.png)

**Testing - Push** (import code: n66h)
Pushes the virtual button every 30 seconds.

![image](https://cloud.githubusercontent.com/assets/8474048/26562085/4ef0ca6e-4491-11e7-8c1a-f568d56845b5.png)

It didn't take long for the "Changes To" piston to miss events. After 10 minutes it missed 8 events.

![image](https://cloud.githubusercontent.com/assets/8474048/26562092/5dc24464-4491-11e7-87d8-b68385faa9c5.png)

When it missed the events it had this in the logs... Notice that "changes_to on" evaluates to false.

```
5/26/2017, 6:29:08 PM +583ms
+1ms	╔Received event [Test Button].switch = on with a delay of 30ms
+210ms	║RunTime Analysis CS > 18ms > PS > 177ms > PE > 15ms > CE
+223ms	║Runtime (31439 bytes) successfully initialized in 177ms (v0.1.0b1.20170524) (220ms)
+225ms	║╔Execution stage started
+385ms	║║Comparison on changes_to on = false (1ms)
+387ms	║║Condition #6 evaluated false (10ms)
+388ms	║║Condition group #1 evaluated false (state did not change) (13ms)
+428ms	║╚Execution stage complete. (203ms)
+444ms	╚Event processed successfully (444ms)


5/26/2017, 6:29:08 PM +614ms
+2ms	╔Received event [Test Button].switch = off with a delay of 56ms
+182ms	║RunTime Analysis CS > 21ms > PS > 147ms > PE > 14ms > CE
+194ms	║Runtime (31440 bytes) successfully initialized in 147ms (v0.1.0b1.20170524) (192ms)
+195ms	║╔Execution stage started
+211ms	║║Comparison off changes_to on = false (1ms)
+213ms	║║Condition #6 evaluated false (8ms)
```

After 2 hours...

![image](https://cloud.githubusercontent.com/assets/8474048/26562110/7d24caac-4491-11e7-985d-e6b58e3500ba.png)

After a long time...

![image](https://cloud.githubusercontent.com/assets/8474048/26562127/b477a204-4491-11e7-84f7-b53424549882.png)

Forum Post: https://community.smartthings.com/t/private-webcore-momma-wants-grandkids-channel-6/87598/589?u=whoismoses

**Comment by ady624** [comment]
The problem lies in the mesh network and most importantly, the DTH. There is no such thing as a momentary switch. That should be called a BUTTON and it should ride on the Button capability. webCoRE acknowledges momentary attributes and uses special logic to deal with them. In essence, button gets pushed several times but the attribute does not actually change. In your example above, the off event comes milliseconds BEFORE the on event, you have race conditions that ST just cannot handle. Solutions are: build a proper DTH that uses the Button capability, not a rapidly flipping on/of (switches are bistables, not monostables - they are not, by definition, momentary). Make the switch flip slower (not a proper solution), use conditions instead of triggers because if you get the events out of order, you will definitely miss triggers (the attribute changes less). I am afraid there is nothing I can do to help, sorry.
