### ISSUE TITLE
Can't save selected devices in new SmartThings app

### ISSUE THREAD

**Issue by brianegge** [ady624/webCoRE#111]
Only "cancel" is available in the new SmartApp. I can no longer run the old (working) SmartThings app to manage the webCORE smartapp.

It does appear to save, even though "Cancel" is the only option available in the GUI

![IMG_6925](https://user-images.githubusercontent.com/175930/91508416-76e21f80-e8a5-11ea-99c2-3e5eaccfa891.png)
![IMG_6926](https://user-images.githubusercontent.com/175930/91508425-7cd80080-e8a5-11ea-828c-0dce15f69e44.png)

**Comment by mikechadwwug** [comment]
Try touching at the top where is says webCoRE.  I did this and it took me back to the main app screen.  I found it by mistatke.  I was then had a Save button.

**Comment by brianegge** [comment]
I tried without any luck on the iPhone. Maybe it's OK on Android devices with a back button.

**Comment by idpaterson** [comment]
There does not seem to be much that we can do here, the new ST app gets confused after returning from the webCoRE Storage smart app. It saves the settings but is certainly confusing.

When you tap Available devices on the main settings screen the next screen is generated by the webCoRE Storage smart app. Cancelling out of that screen gets you back to the webCoRE smart app, but the ST app is confused and shows Cancel rather than Next at the bottom of the screen. Cancelling shows the Discard changes prompt and dumps you back out to the Smart Apps list whereas Next (in cases where you did not tap through Available devices) would normally send you back to the webCoRE engine block/dashboard/settings main screen. Unfortunately there is no code available in the smart app to control this, so it would have to be resolved in the ST mobile app.

**Comment by brianegge** [comment]
Thank you. Fortunately, the storage app does save the settings, or I would be quite stuck.
