### ISSUE TITLE
Array index 0 inaccessible in for-loop

### ISSUE THREAD

**Issue by wuboy511** [ady624/webCoRE#25]
I setup an array of integers and try to access them in a for loop. On the first iteration using $index, the array[0] returns 0 (or null if I log it alone without strings) no matter what. I can access array[0] without using index variable.

Example: 
![arraytestpiston](https://user-images.githubusercontent.com/6404695/30436547-38459490-9921-11e7-9a50-51b8eb49f3ce.png)

9/14/2017, 7:48:24 AM +34ms
--
+374ms | ║index: 0; array: 0
+417ms | ║index: 1; array: 79
+456ms | ║index: 2; array: 77
+503ms | ║array[0]: 81; array[1]: 79; array[2] 77

**Comment by idpaterson** [comment]
I noticed the same a few weeks ago, it will work as expected if you use an integer variable instead of the global `$index`. There is a lot more testing and discussion [over here](https://community.webcore.co/t/cant-access-value-at-arrays-zero-index-in-a-for-loop-using-the-default-index-variable/442).

**Comment by wuboy511** [comment]
Thanks for the link. I'll switch to using an index counter variable for now.
