### ISSUE TITLE
webcore forum innacessible?

### ISSUE THREAD

**Issue by popepay** [ady624/webCoRE#28]
Hello,

I have been trying to sign up for the webcore forum but no matter what I try (2 different browsers, fill all fields/only some/...), the sign up button remains greyed out. 

is this normal?

![screen shot 2017-10-01 at 3 09 02 pm](https://user-images.githubusercontent.com/17018621/31059636-89b76ee2-a6ba-11e7-8a66-0d4a535340a4.png)

**Comment by idpaterson** [comment]
This is a pretty bad interface... you actually need to scroll down in the form area to view two additional fields. I'm going to see if I can make the dialog box expand to the correct height to avoid that interior scrolling.

**Comment by idpaterson** [comment]
I updated the theme to remove the interior scrolling in this and similar dialogs. Instead, the entire dialog box now scrolls so that the submit buttons are only visible once you have scrolled to the bottom of the form.

When the form is taller than the browser viewport it will now look like this:
![screen shot 2017-10-01 at 8 25 26 pm](https://user-images.githubusercontent.com/507058/31060762-ed86c568-a6e6-11e7-97b9-0cc8f4a2f47c.png)

**Comment by ScottChapman** [comment]
What's the URL for the community? Couldn't find it. Also link to create a new account on the dashboard page doesn't appear to work.

**Comment by idpaterson** [comment]
https://community.webcore.co and username/password accounts aren't supported yet so that register link is just an unfortunately confusing placeholder.
